---
abstract: '(EXPERIMENTAL) run disttest with local lib'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Module::Build::Pluggable::CPANfile: 0.02
  Module::Build::Pluggable::GithubMeta: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.40
  Module::Build::Pluggable: 0
  Module::Build::Pluggable::CPANfile: 0.02
  Module::Build::Pluggable::GithubMeta: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Pluggable-DistTestLibCoreOnly
no_index:
  directory:
    - inc
provides:
  Module::Build::Pluggable::DistTestLibCoreOnly:
    file: lib/Module/Build/Pluggable/DistTestLibCoreOnly.pm
    version: v0.0.6
requires:
  App::cpanminus: 0
  Module::Build::Pluggable: 0.08
  lib::core::only: 0
  parent: 0
  perl: 5.008005
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.6
